use_frameworks!

platform :ios, '9.0'

target 'CHCUIKit_Example' do
  pod 'CHCUIKit', :path => '../'

  target 'CHCUIKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
